### ISSUE TITLE
Problème de connexion

### ISSUE THREAD

**Issue by zhenren5** [EmixamPP/guidance-queue#1]
J'ai l'**erreur de connexion avec le serveur** quand je voulais me connecter avec ma tablette.

**Comment by EmixamPP** [comment]
C'est un problème avec le wifi d'eduroam sur la Plaine, je crois. Il est parfois extrêmement lent et instable. Et du coup déclenche la fermeture du socket réseau. J'ai déjà eu ce souci, et simplement actualiser la page ou fermer l'onglet, permet de rouvrir une connexion propre avec le serveur la fois d'après.

Après avec les appareils mobiles (comme ta tablette), il faut faire attention à ce qu'ils ne rentrent pas en veille.  Est-ce que c'était ton cas ? Car ils mettent alors aussi le navigateur en veille profonde qui coupe alors la connexion avec le serveur. Il faut donc ensuite se reconnecter en actualisant la page.

Je pourrai faire un système niveau serveur qui essaye de restaurer les connexions après des erreurs du réseau. Mais ça deviendrait extrêmement plus complexe.

**Comment by zhenren5** [comment]
ah oui, c'est probablement ça ! tkt ne t'embête pas avec ça, la prochaine fois je porterai mon ordinateur portable.

**Comment by EmixamPP** [comment]
Ou alors le plus simple, c'est d'augmenter la durée d'inactivité avant la mise en veille. Voir de la désactiver quand tu fais guidance.

**Comment by zhenren5** [comment]
ok, mercii :)
